- hosts: webserver
  become: true
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Copy index.html to Apache document root
      copy:
        src: index.html
        dest: /var/www/html

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Change Apache port number
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen "
        line: "Listen 8080"
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

