- hosts: webserver
  become: true
  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
      
        - docker
        - nginx

